name: nocknock
description: "NockNock collaborative post-it reminders and tasks."
publish_to: "none"

version: 1.0.0+502

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  dio: ^5.11.0
  socket_io_client: ^3.1.6
  uuid: ^4.6.0
  intl: ^0.20.2
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  firebase_analytics: ^12.4.6
  firebase_crashlytics: ^5.2.7
  google_sign_in: ^7.2.0
  in_app_update: ^5.0.0
  shared_preferences: ^2.5.5
  flutter_quill: ^11.5.1
  image_picker: ^1.2.1
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.2.0
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/nocknock-logo.png
    - assets/note_backgrounds/
